bootJar { enabled = true }
jar { enabled = false }

dependencies {
    implementation project(':portfolio-core')
    implementation project(':portfolio-domain:domain-mysql')
    implementation project(':portfolio-domain:domain-redis')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
