bootJar {
    enabled = false
}
jar {
    enabled = true
}

dependencies {
    /* Jackson DataType */
    api group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.18.0'
    api 'com.fasterxml.jackson.core:jackson-databind'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
